services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./assignment1:/var/www/html/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password

    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: assignment1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080